### ISSUE TITLE
Error Running the HairFastGAN

### ISSUE THREAD

**Issue by ialhabbal** [FusionBrainLab/HairFastGAN#15]
Received this error:

(venv) G:\HairFastGAN>python main.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
G:\HairFastGAN\venv\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "G:\HairFastGAN\main.py", line 9, in <module>
    from hair_swap import HairFast, get_parser
  File "G:\HairFastGAN\hair_swap.py", line 13, in <module>
    from models.Alignment import Alignment
  File "G:\HairFastGAN\models\Alignment.py", line 8, in <module>
    from models.Encoders import RotateModel
  File "G:\HairFastGAN\models\Encoders.py", line 9, in <module>
    from models.Net import FeatureEncoderMult, IBasicBlock, conv1x1
  File "G:\HairFastGAN\models\Net.py", line 9, in <module>
    from models.stylegan2.model import Generator
  File "G:\HairFastGAN\models\stylegan2\model.py", line 11, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "G:\HairFastGAN\models\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "G:\HairFastGAN\models\stylegan2\op\fused_act.py", line 10, in <module>
    fused = load(
  File "G:\HairFastGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "G:\HairFastGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "G:\HairFastGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1610, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "G:\HairFastGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2014, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "G:\HairFastGAN\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1780, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by bhavesh-hirpara** [comment]
You need to try 
`pip3 install torch=1.13.1 torchvision=0.14.1 --index-url https://download.pytorch.org/whl/cu118`

**Comment by ButyAfter** [comment]
好像还是不行

**Comment by Ja-sonYun** [comment]
Try without specifying the version like below if someone gets stuck on this
```
pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```
I didn't check for problems that could occur from the version mismatch (it will update PyTorch to 2.X.X), but at least I was able to run the demo.

**Comment by maximkm** [comment]
Thank you for reporting this issue. I apologize for the inconvenience you're experiencing while trying to run the method.

Based on the error message you provided, it appears that there's a CUDA configuration problem on your Windows system, which is preventing the ninja build process from completing successfully.

To resolve this, I recommend using Windows Subsystem for Linux (WSL). This approach has been tested by our team and should help avoid environment-related issues. Here's a step-by-step guide to get you started:

1. Install WSL following the instructions at: https://learn.microsoft.com/en-us/windows/wsl/install

2. Once WSL is set up, install Python 3.10 within your WSL environment.

3. Use poetry to install all required packages. This will ensure a consistent and isolated environment for the project.

4. Try running the method again within this WSL environment.

If you encounter any difficulties with this process or if the error persists after following these steps, please don't hesitate to reach out. Provide details about any new errors or issues you face, and I'll be glad to assist you further.
